app:
  jwtSecret: "Secret123Secret123Secret123Secret123Secret123Secret123Secret123"
  jwtExpirationMs: 3600000
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/taskManager}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate.ddl-auto: update